### ISSUE TITLE
Support EC2 Instance Connect Send SSH Key

### ISSUE THREAD

**Issue by bcbrockway** [cloudposse/terraform-aws-eks-node-group#108]
## Describe the Feature

Have the module set up SSH access when a security group is supplied but without necessarily needing an SSH keypair (see [here](https://github.com/cloudposse/terraform-aws-eks-node-group/blob/37d23d39f4295b841dc0d87775a710b507655c46/main.tf#L12))

## Expected Behavior

Module will set up SSH access if `ssh_access_security_group_ids` is provided without needing `ec2_ssh_key_name`.

## Use Case

Currently an SSH keypair is required before the module will set up SSH access but we prefer to use `aws ec2-instance-connect send-ssh-public-key` as-and-when we need to access an EC2 instance. We can still send other keys to the instance if we add a random key to the module but that opens the instance up to that keypair permanently rather than temporarily and on-demand.

**Comment by nitrocode** [comment]
Using ssm over ssh is the preferred pattern. Why would you want to want to enable ssh?
