### ISSUE TITLE
Expose tags_all output

### ISSUE THREAD

**Issue by KhannaAbhinav** [cloudposse/terraform-aws-eks-node-group#111]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

Can you please add tags_all output to the module

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#tags_all

## Expected Behavior

Module should output tags_all field.

## Use Case

This will bring current module in line with the terraform resource. This will also help to solve the #109 

## Describe Ideal Solution

tags_all should be output

## Alternatives Considered

NA

## Additional Context

NA

**Comment by Nuru** [comment]
Closed by #118
