### ISSUE TITLE
ASG tags with "false" value cluster_autoscaler option

### ISSUE THREAD

**Issue by eliasmachado21** [cloudposse/terraform-aws-eks-node-group#113]
## Describe the Bug
I'm trying to create a ASG without Cluster AutoScaler option enable

## Expected Behavior
The ASG without tags for autodiscover CAS

## Steps to Reproduce
1. Create a nodegroup with the option [input_cluster_autoscaler_enabled](https://github.com/cloudposse/terraform-aws-eks-node-group#input_cluster_autoscaler_enabled) in false value

## Screenshots
ASG tags
![Captura de Pantalla 2022-04-26 a la(s) 16 37 58](https://user-images.githubusercontent.com/86381954/165562652-1e053a65-62ea-4118-bf34-188ab08951db.png)

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
- Module version "0.27.3"

**Comment by Gowiem** [comment]
@eliasmachado21 Great point and should be an easy fix! Would you be willing to put together a small PR to address [by changing this line](https://github.com/cloudposse/terraform-aws-eks-node-group/blob/master/main.tf#L22) to have the value be assigned from `local.autoscaler_enabled`

**Comment by Nuru** [comment]
> @eliasmachado21 Great point and should be an easy fix! Would you be willing to put together a small PR to address [by changing this line](https://github.com/cloudposse/terraform-aws-eks-node-group/blob/master/main.tf#L22) to have the value be assigned from `local.autoscaler_enabled`

@Gowiem That is not a sufficient fix for a couple of reasons:

- The value of the tag key is typically ignored. The autoscaler just looks for the presence of the tag key.
- Those tags are already getting toggled:
https://github.com/cloudposse/terraform-aws-eks-node-group/blob/8d415522042e8547caa31afb49d95bc640e32cf2/main.tf#L38


I don't know for sure where these tags are coming from, but they are standard tags and I strongly suspect they are getting created by the EKS cluster itself. See https://github.com/aws/containers-roadmap/issues/608#issuecomment-639549332

**Comment by Gowiem** [comment]
@Nuru Ah gotcha -- I didn't read deeply enough into how `autoscaler_enabled` is being used, apologies. Also didn't know the context around the value being ignored -- That is not great. Anyway, thanks on weighing in.
