### ISSUE TITLE
Is it possible to make terraform ignore desired_size

### ISSUE THREAD

**Issue by dreamrace** [cloudposse/terraform-aws-eks-node-group#12]
First of all, thank you for the work in all these terraform modules, it's been a great help to my work.

*Use case:* On a eks with cluster-autoscaler
*Behavior:* Updated desired size get overridden by terraform on `apply`
*Desired behavior*: desired_size is ignore by terraform

Is it possible (or a good idea) to make `desired_size` a ignore attribute.
Best option would be to create a flag to conditionally ignore it, but since https://github.com/hashicorp/terraform/issues/3116 lifecycle block does not allow variables.

Example:
```terraform
## Add ti resource.aws_eks_node_group.default
  lifecycle {
    ignore_changes = [
      scaling_config["desired_size"],
    ]
  }
```

**Comment by mbebjak** [comment]
Hi @dreamrace adding following code to node_group config works for me:
```
lifecycle {
    ignore_changes = [scaling_config.0.desired_size]
  }
```

**Comment by maxgio92** [comment]
Hi all, I just opened a [PR](https://github.com/cloudposse/terraform-aws-eks-node-group/pull/17) for this.

**Comment by sunnyoswalcro** [comment]
@maxgio92 @mbebjak having managed nodegroup:
```
desired: 1
max: 1
min: 1
```

if i add below:
```
lifecycle {
  ignore_changes = [scaling_config.0.desired_size]
}
```

and then update nodegroup to :
```
desired: 2
max: 2
min: 2
```

i get error:
```
Error: error updating EKS Node Group (XXXXX) config: InvalidParameterException: Minimum capacity 2 can't be greater than desired size 1
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "b80be2de-b265-4388-bdff-6e3582706117"
│   },
│   ClusterName: "onegha",
│   Message_: "Minimum capacity 2 can't be greater than desired size 1",
```

idea is to have cluster autoscaler manage desired and terraform plan to not show changes to desired size and apply works if we want to change min/max .
