### ISSUE TITLE
oidc provider setup

### ISSUE THREAD

**Issue by bytearchive** [cloudposse/terraform-aws-eks-node-group#128]
how do I setup the callback urls etc for oidc provider i.e. congnito?

**Comment by Nuru** [comment]
OIDC is not set up here, at the node group level. It is set up at the cluster level. These might help:

- [terraform-aws-eks-cluster](https://github.com/cloudposse/terraform-aws-eks-cluster)
- [Component: eks/cluster](https://docs.cloudposse.com/components/library/aws/eks/cluster/)
