### ISSUE TITLE
Propagate the default tags from aws provider

### ISSUE THREAD

**Issue by polak785** [cloudposse/terraform-aws-eks-node-group#156]
### Describe the Feature

With ressources related to the AWS provider, we can set default tags as explain in https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider

Is this possible to your module to take them into account in order to propagate them to the ressources created ?

Otherwise it works with an explicit declaration tag : 
```terraform
module "nodegroup" {
  source  = "cloudposse/eks-node-group/aws"
...
  tags = merge(
    local.default_tags,
    { other = "value" }
)
```
Thus not a big deal but just wanted to know if you plan to add it automatically or I we need to explicit set them. 

Thank you :)

### Expected Behavior

Use the default tags declared in AWS provider, cf. https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider

### Use Case

We use the default tag to propagate a tag that indicates from which git project and in which folder the ressource configuration comes from.

### Describe Ideal Solution

Instead of explicit declared default tags to use in the module, use them automatically

**Comment by Nuru** [comment]
This module does not create an Autoscaling Group (EKS does that automatically), and in all other cases the default tags are automatically propagated, so there is nothing for us to do here.
