### ISSUE TITLE
EKS Node Launch Template support

### ISSUE THREAD

**Issue by dotCipher** [cloudposse/terraform-aws-eks-node-group#24]
## Describe the Feature

The [eks-node-group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#launch_template) resource now supports launch templates.  

See associated [aws post](https://aws.amazon.com/blogs/containers/introducing-launch-template-and-custom-ami-support-in-amazon-eks-managed-node-groups/) as well as [eks launch templates docs](https://docs.aws.amazon.com/eks/latest/userguide/launch-templates.html) for more information.

## Expected Behavior

1. Define `launch_template` somewhere in call-site of this module
1. Reference `launch_template` output within attribute of `cloudposse/terraform-aws-eks-node-group`

## Use Case

I'd like to be able to add user data (ie. install SSM agent) to my EKS managed node groups, and I am unable to do that without adding launch templates.  

## Describe Ideal Solution

There should be a `launch_template` attribute that is 'settable' for the module

## Alternatives Considered

Only alternative would be to remove dependency to this module and hand write it 😛 

## Additional Context

- [AWS discussion of adding launch template support to EKS](https://github.com/aws/containers-roadmap/issues/585)
- [`launch_template` terraform resource](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template)

**Comment by dotCipher** [comment]
Seems like this might be dependant on the version bump PR: https://github.com/cloudposse/terraform-aws-eks-node-group/pull/25

**Comment by dotCipher** [comment]
FWIW, I'd gladly help write the PR, can someone point me in the right direction for the testing workflow used? ie. what commands to run, etc?

**Comment by danjbh** [comment]
I'm going to push to get this knocked out today and would appreciate another set of eyes & testing when the new PR ready. I'll post it here once it's ready. Stay tuned!

**Comment by danjbh** [comment]
Hey there @dotCipher , I have a first draft of this prepped that allows you to...

1. Completely override the launch template by passing `aws_launch_template.foo.id` and `launch_template.foo.version` to the module
2. Override *only* the userdata by passing it to the module as a typical, b64 encoded string
3. Not do anything extra and we'll use a minimal, default `aws_launch_template` (and default userdata) -- the primary enhancement here being that it adds the `tag_specifications` config option that will pass on our tags to `instances`, `volumes`, and `elastic-gpu`

Beyond that, there is one snag I ran into w/ the instance types -- a launch template won't accept a list of instance types, which the module is currently accepting. The `aws_eks_node_group` resource actually accepts a list, although the documentation says it can only handle a single value currently (woohoo).

Anyhow, I need to sort through that bit before I can push another PR and I may not have it ready until tomorrow. But definitely let me know your thoughts on the above in the meantime!

**Comment by danjbh** [comment]
Hey there @dotCipher , feel free to check out #27

**Comment by dotCipher** [comment]
Awesome, thanks @danjbh! I posted some questions on the PR

**Comment by danjbh** [comment]
Hey @dotCipher , just a friendly warning here -- I found some issues w/ the latest version of the module after merging that PR. I would hold off on using the module until I can get things fixed.

**Comment by dotCipher** [comment]
Thanks for the heads-up @danjbh, I'll keep a look out for your fix

**Comment by dotCipher** [comment]
Out of curiosity, what were the issues you found?

**Comment by danjbh** [comment]
> Out of curiosity, what were the issues you found?

I didn't realize that if we don't specify our own custom AMI, that it actually appends it's own bootstrap.sh script in userdata AFTER the userdata script that we supply. So it was effectively trying to run bootstrap.sh twice, which was... undesirable :)

**Comment by dotCipher** [comment]
Does the AMI get set to custom version if the userdata is set? Would I be able to use the module as-is now if I am not using a custom AMI?

**Comment by danjbh** [comment]
Nope, we can set our userdata without specifying a custom AMI, so you should be able to install your SSM agent using `0.10.0` of the module by setting the before userdata variable.

**Comment by dotCipher** [comment]
Ah ok great thanks!

**Comment by dotCipher** [comment]
Feel free to close this out then, appreciate the help!  I'll follow up with a new ticket if I have any issues
