### ISSUE TITLE
examples/complete/fixtures.us-east-2.tfvars kubeconfig file

### ISSUE THREAD

**Issue by omerfsen** [cloudposse/terraform-aws-eks-node-group#3]
The tfvars file contains

kubeconfig_path = "/.kube/config"

but this can't be created so it fails I think it should be

kubeconfig_path = "~/.kube/config"

**Comment by aknysh** [comment]
@omerfsen 
this is for our Terratest which runs on Codefresh in our `geodesic` container.
It works OK.
In your code, you definitely need to set it up to the path that works for you.
