### ISSUE TITLE
Resource diff on refactor of IDs

### ISSUE THREAD

**Issue by dotCipher** [cloudposse/terraform-aws-eks-node-group#38]
## Describe the Bug
The refactor that happened in https://github.com/cloudposse/terraform-aws-eks-node-group/commit/cab5114a6054b5f3e5efea07e36d6f0c65ff8d9a seems like it changes the IDs of resources forcing them to recreate.

## Expected Behavior

Updating the version of the module at the call site shouldn't make this change (right?).

Seems like the resources in question are (see `autoscaler` -> `autoscale`):
- `module.node-group.aws_iam_policy.amazon_eks_worker_node_autoscaler_policy`
  - Renamed to: `module.node-group.aws_iam_policy.amazon_eks_worker_node_autoscale_policy`
- `module.node-group.aws_iam_role_policy_attachment.amazon_eks_worker_node_autoscaler_policy`
  - Renamed to: `module.node-group.aws_iam_role_policy_attachment.amazon_eks_worker_node_autoscale_policy`

## Steps to Reproduce
1. Run a `terraform apply` using `v0.11.3`
2. Checkout to `v0.12.0-rc1`
3. `terraform plan` should show the name diff

## Screenshots
<img width="920" alt="Screen Shot 2020-10-27 at 4 43 18 PM" src="https://user-images.githubusercontent.com/3977074/97359698-8cf36880-1873-11eb-8a1a-ea5c60c72659.png">
<img width="799" alt="Screen Shot 2020-10-27 at 4 43 05 PM" src="https://user-images.githubusercontent.com/3977074/97359704-8ebd2c00-1873-11eb-8c20-7201bfef574e.png">

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: OSX
 - Version 10.15.7

**Comment by dotCipher** [comment]
Closing as it's intentional

**Comment by Nuru** [comment]
@dotCipher This was an intentional change, part of switching from `enable_cluster_autoscaler` to `cluster_autoscaler_enabled`. It is also a trivial change that can be applied to a running cluster with no disruption of service.
