### ISSUE TITLE
Add cluster autoscaling iam policy

### ISSUE THREAD

**Issue by EamonKeane** [cloudposse/terraform-aws-eks-node-group#4]
This might overlap with other cloudposse modules, but in a cluster with just managed nodes, the cluster iam inline policy needs to be added to the nodes for the autoscaler to work.

Or perhaps it should be left off the node and added to the pod via IRSA.

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeTags",
                "autoscaling:SetDesiredCapacity",
                "autoscaling:TerminateInstanceInAutoScalingGroup"
            ],
            "Resource": "*"
        }
    ]
}`

**Comment by Nuru** [comment]
This was closed by #13
