### ISSUE TITLE
Error when configured multiple instance types

### ISSUE THREAD

**Issue by maxgio92** [cloudposse/terraform-aws-eks-node-group#8]
Hi,
I don't know if this is useful but I'm falled into this issue when providing two instance types:
```
data.aws_iam_policy_document.assume_role[0]: Refreshing state...

Error: instance_types: attribute supports 1 item maximum, config has 2 declared

  on main.tf line 66, in resource "aws_eks_node_group" "default":
  66: resource "aws_eks_node_group" "default" {
```

At the moment I did not try to solve this issue since I'm opening a PR on another one :-)

**Comment by woz5999** [comment]
This seems to be a result of bad AWS API naming and the various downstream projects remaining consistent with a bad name: https://github.com/terraform-providers/terraform-provider-aws/issues/11414

**Comment by Nuru** [comment]
It is an AWS EKS limitation that you can only supply a single instance type, even though launch templates in general support multiple instance types, and the API name follows the launch template API name and is plural. 

We have added a validation error message about this, which is about all we can do. 

Closing, as there is not much more we can do about this.
