### ISSUE TITLE
Bug: Disabling this resource fails (local.create_role)

### ISSUE THREAD

**Issue by cdobbyn** [cloudposse/terraform-aws-eks-node-group#88]
## Describe the Bug
If you set `enabled = false` when variable `node_role_arn` is not specified terraform will fail to plan. This is due to this line:
https://github.com/cloudposse/terraform-aws-eks-node-group/blob/master/main.tf#L59

The problem is that when `enabled = false` this tries to lookup a resource in a list that doesn't exist. 

A workaround exists where you can set `node_role_arn = ["any random string"]` to make terraform plan.

## Expected Behavior
The resource is cleanly removed as expected without a workaround.

## Steps to Reproduce
1. Create this module somewhere without specifying variable `node_role_arn`
2. Try to remove it with `enabled = false`
3. Run a terraform plan

## Screenshots
If applicable, add screenshots or logs to help explain your problem.
```
╷
│ Error: Invalid index
│ 
│   on .terraform/modules/eks_ephemeral_20210901.eks_node_group/main.tf line 59, in locals:
│   59:     node_role_arn = local.create_role ? join("", aws_iam_role.default.*.arn) : var.node_role_arn[0]
│     ├────────────────
│     │ var.node_role_arn is empty list of string
│ 
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
```

## Environment:
 - OS: Ubuntu
 - Version: 20.04

**Comment by cdobbyn** [comment]
This probably has to look like
```hcl
node_role_arn = local.create_role ? join("", aws_iam_role.default.*.arn) : (
  var.enabled ? var.node_role_arn[0] : ""
)
```

**Comment by runningman** [comment]
encountered the same issue, the fix worked for me it would be nice to see it merged
