### ISSUE TITLE
Bug: continuously add cluster owned tag

### ISSUE THREAD

**Issue by cdobbyn** [cloudposse/terraform-aws-eks-node-group#89]
## Describe the Bug
Continuously wants to update cluster owned tag:
```
tags                    = {
    + "kubernetes.io/cluster/my-cluster-name" = "owned"
      # (7 unchanged elements hidden)
}
```
To the following resources:
- `.module.ssh_access[0].aws_security_group.cbd[0]`
- `.aws_launch_template.default[0]`
- `.aws_iam_role.default[0]`
- `.aws_eks_node_group.cbd[0]`

## Expected Behavior
After apply no further changes are required.

## Steps to Reproduce
1. Create node group in terraform
2. Run apply to create it
3. Run apply again, and see that it wants to make changes, apply them
4. Repeat....

## Environment (please complete the following information):
- Terraform 0.14.11
- AWS provider 3.60.0

**Comment by nitrocode** [comment]
This may be a provider bug @cdobbyn

**Comment by nitrocode** [comment]
@cdobbyn were you setting `default_tags` on the provider ? have you been able to reproduce this issue with the 3.x provider ?

**Comment by cdobbyn** [comment]
I have deployed a few more clusters since I wrote this issue and haven't seen the problem. I think this can be closed. Sorry for the slow response.
