### ISSUE TITLE
EBS Optimization

### ISSUE THREAD

**Issue by jrowinski3d** [cloudposse/terraform-aws-eks-node-group#97]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature

I would like a flag to be available to enable `ebs_optimzation` in the launch_template

## Expected Behavior

I would like a flag to be available to enable `ebs_optimzation` in the launch_template

## Use Case

Enable `ebs_optimzation` in the launch_template

## Describe Ideal Solution

Boolean flag to enable `ebs_optimzation`

I tried to push a branch/PR but I am getting access denied. I'm wondering if possible to just add this flag to the `launch_template.tf` to allow users to enable the optimization.

```bash
  ebs_optimzed = local.ebs_optimzed == "" ? false : local.ebs_optimzed
```

**Comment by nitrocode** [comment]
@jrowinski3d thanks for creating the update. have you considered opening a PR for this? if you do, Id be fair to review

**Comment by jrowinski3d** [comment]
hi @nitrocode , I get `access denied` when I try to push a branch for PR creation.

**Comment by nitrocode** [comment]
@jrowinski3d you'll have to fork this module, create a branch off your fork, commit changes to it, and PR the branch to this repo to submit the patch

**Comment by jrowinski3d** [comment]
@nitrocode I think this would be a lot easier to drive this through a simple branch/PR process. Hope this will get into the module one day. If this is the process for Cloudposse then I get it. I do enjoy the use of the modules and appreciate the work going into them.
